#!/usr/bin/with-contenv sh
curl https://dl.minio.io/client/mc/release/linux-amd64/mc > /usr/bin/mc
chmod +x /usr/bin/mc
echo "mc config host add media ${MEDIA_ENDPOINT} ${MEDIA_ACCESS_KEY} ${MEDIA_SECRET_KEY}"
mc config host add media ${MEDIA_ENDPOINT} ${MEDIA_ACCESS_KEY} ${MEDIA_SECRET_KEY} --api s3v4
